# Generated by Django 3.1.5 on 2021-01-24 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210124_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='like_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
